#!/bin/sh

# clean-up components from v4
if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_reapack64.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_reapack64.dylib
fi

# clean-up components from v5
if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_reapack-arm64.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_reapack-arm64.dylib
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_reapack-x86_64.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_reapack-x86_64.dylib
fi
