#!/bin/sh

# remove components from v4
if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/sws_python.py ]; then
  rm -f ~/Library/Application\ Support/REAPER/UserPlugins/sws_python.py
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/sws_python32.py ]; then
  rm -f ~/Library/Application\ Support/REAPER/UserPlugins/sws_python32.py
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/sws_python64.py ]; then
  rm -f ~/Library/Application\ Support/REAPER/UserPlugins/sws_python64.py
fi

if [ -f ~/Library/Application\ Support/REAPER/Scripts/sws_python32.py ]; then
  rm -f ~/Library/Application\ Support/REAPER/Scripts/sws_python32.py
fi

# remove components from v4
if [ -f ~/Library/Application\ Support/REAPER/Scripts/sws_python.py ]; then
  rm -f ~/Library/Application\ Support/REAPER/Scripts/sws_python.py
fi

if [ -f ~/Library/Application\ Support/REAPER/Scripts/sws_python64.py ]; then
  rm -f ~/Library/Application\ Support/REAPER/Scripts/sws_python64.py
fi
