#!/bin/sh

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_api.lua ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_api.lua
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_api_readme.txt ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_api_readme.txt
fi

if [ -d ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_api ]; then
	rm -rf ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_api
fi
