#!/bin/sh

# remove components from v4
if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws.dylib
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws_extension.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws_extension.dylib
fi

# remove components from v5
if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws-arm64.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws-arm64.dylib
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws-x86_64.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws-x86_64.dylib
fi
