#!/bin/sh

if [ -d /Library/Audio/Plug-Ins/Components/Soundboard.component ]; then
	sudo rm -rf /Library/Audio/Plug-Ins/Components/Soundboard.component
fi

if [ -d ~/Library/Application\ Support/REAPER/UserPlugins/Soundboard.component ]; then
	rm -rf ~/Library/Application\ Support/REAPER/UserPlugins/Soundboard.component
fi

if [ -d ~/Library/Application\ Support/REAPER/UserPlugins/FX/Soundboard.component ]; then
	rm -rf ~/Library/Application\ Support/REAPER/UserPlugins/FX/Soundboard.component
fi
