#!/bin/sh


echo "Installing the Ultraschall REAPER Theme..."
unzip -o "$HOME/Library/Application Support/Ultraschall/Theme/Ultraschall_4.1.ReaperConfigZip" -d "$HOME/Library/Application Support/REAPER"

if [ $? -ne 0 ]; then
  echo "Failed to install Ultraschall."
  exit -1
fi

exit 0
