#!/bin/sh

if [ -d "$HOME/Library/Application Support/REAPER" ]; then
  BACKUP_TIMESTAMP=$(date -ju "+%Y%m%dT%H%M%S")
  BACKUP_FOLDER="$HOME/Library/Application Support/Ultraschall/Backups/$BACKUP_TIMESTAMP"
  mkdir -p "$BACKUP_FOLDER"
  cp -r "$HOME/Library/Application Support/REAPER" "$BACKUP_FOLDER"
  if [ $? -eq 0 ]; then
    echo "Your current REAPER configuration has been saved to $BACKUP_FOLDER."
  else
    echo "Failed to backup your current REAPER configuration. Aborting installation..."
    exit -1
  fi
fi
