#!/bin/sh

# Remove legacy components (< 3.1)
if [ -f /Library/Application\ Support/REAPER/UserPlugins/reaper_ultraschall.dylib ]; then
	sudo rm -f /Library/Application\ Support/REAPER/UserPlugins/reaper_ultraschall.dylib
fi

if [ -f /Library/Application\ Support/REAPER/UserPlugins/reaper_sws_extension.dylib ]; then
	sudo rm -f /Library/Application\ Support/REAPER/UserPlugins/reaper_sws_extension.dylib
fi

if [ -f /Library/Application\ Support/REAPER/UserPlugins/sws_python.py ]; then
	sudo rm -f /Library/Application\ Support/REAPER/UserPlugins/sws_python.py
fi

if [ -f /Library/Application\ Support/REAPER/UserPlugins/sws_python32.py ]; then
	sudo rm -f /Library/Application\ Support/REAPER/UserPlugins/sws_python32.py
fi

if [ -f /Library/Application\ Support/REAPER/UserPlugins/sws_python64.py ]; then
	sudo rm -f /Library/Application\ Support/REAPER/UserPlugins/sws_python64.py
fi

# Remove current components (3.1)
if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_ultraschall.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_ultraschall.dylib
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws_extension.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws_extension.dylib
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/sws_python.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/sws_python.py
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/sws_python32.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/sws_python32.py
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/sws_python64.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/sws_python64.py
fi

if [ -d /Library/Audio/Plug-Ins/Components/StudioLinkOnAir.component ]; then
	rm -rf /Library/Audio/Plug-Ins/Components/StudioLinkOnAir.component
fi

if [ -d /Library/Audio/Plug-Ins/Components/StudioLink.component ]; then
	sudo rm -rf /Library/Audio/Plug-Ins/Components/StudioLink.component
fi

if [ -d /Library/Audio/Plug-Ins/Components/Soundboard.component ]; then
	sudo rm -rf /Library/Audio/Plug-Ins/Components/Soundboard.component
fi

# Remove new components (4.0)
if [ -d ~/Library/Application\ Support/REAPER/UserPlugins/FX ]; then
	rm -rf ~/Library/Application\ Support/REAPER/UserPlugins/FX
fi

if [ -d ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_api ]; then
	rm -rf ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_api
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_api.lua ]; then
	rm -rf ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_api.lua
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_api_readme.txt ]; then
	rm -rf ~/Library/Application\ Support/REAPER/UserPlugins/ultraschall_api_readme.txt
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_js_ReaScriptAPI64.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_js_ReaScriptAPI64.dylib
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_reapack64.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_reapack64.dylib
fi

if [ -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws-x86_64.dylib ]; then
	rm -f ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws-x86_64.dylib
fi

if [ -f ~/Library/Application\ Support/REAPER/Scripts/sws_python.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/sws_python.py
fi

if [ -f ~/Library/Application\ Support/REAPER/Scripts/sws_python32.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/sws_python32.py
fi

if [ -f ~/Library/Application\ Support/REAPER/Scripts/sws_python64.py ]; then
	rm -f ~/Library/Application\ Support/REAPER/Scripts/sws_python64.py
fi
