#!/bin/sh

if [ -d /Library/Audio/Plug-Ins/Components/StudioLinkOnAir.component ]; then
	sudo rm -rf /Library/Audio/Plug-Ins/Components/StudioLinkOnAir.component
fi

if [ -d ~/Library/Application\ Support/REAPER/UserPlugins/StudioLinkOnAir.component ]; then
	rm -rf ~/Library/Application\ Support/REAPER/UserPlugins/StudioLinkOnAir.component
fi

if [ -d ~/Library/Application\ Support/REAPER/UserPlugins/FX/StudioLinkOnAir.component ]; then
	rm -rf ~/Library/Application\ Support/REAPER/UserPlugins/FX/StudioLinkOnAir.component
fi
