name: ultraschall-macos

on:
  push:

jobs:
  test-macos:
    name: Test macOS installer
    # runs-on: macos-11.0
    runs-on: macos-10.15

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run installer script
      run: |
        cd macos
        ./build.sh

    - name: find files
      run: |
        find . -iname \*.dmg 2>/dev/null
        find / -iname \*.dmg 2>/dev/null
        find . -iname \*.pkg 2>/dev/null


    # - name: Archive production artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: dist-without-markdown
    #       path: |
    #         dist
    #         !dist/**/*.md

