name: macos

on:
  push:

jobs:
  build-macos:
    name: Build macOS installer
    # runs-on: macos-11.0
    runs-on: macos-10.15

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run installer script
      run: |
        cd macos
        ./build.sh


    - uses: actions/upload-artifact@v2
      with:
        name: ultraschall-build-macos
        path: |
          macos/*.dmg
